import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next';


const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans bg-[#101113] text-white`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
